### ISSUE TITLE
v.Size = 0, font CV0 doesn't exist

### ISSUE THREAD

**Issue by Matryan** [Cherry/3D2D-TextScreens#11]
Link to problem:
http://forum.darkrp.com/threads/text-screen-error.5425/

**Comment by Cherry** [comment]
This was fixed quite a while ago - the line reference in the error isn't even valid anymore.

https://github.com/Cherry/3D2D-TextScreens/commit/eb37cbece6d5651e3789714dae7c0c2a7f95fc90

Are you running an older version of the addon by chance?

**Comment by Matryan** [comment]
Ahh crap, I didn't even really look at the line.
Thanks for your help.

**Comment by Cherry** [comment]
No worries! :)
