### ISSUE TITLE
Adding presets feature

### ISSUE THREAD

**Issue by AMD-NICK** [Cherry/3D2D-TextScreens#12]
Subj. It will help in map changing when need to copy 10+ textscreens with server info to new map.

**Comment by Cherry** [comment]
Interesting suggestion. I'll think about it for the future.

**Comment by AMD-NICK** [comment]
Thanks :)

**Comment by Empyr** [comment]
This would be great, maybe a dropdown menu that (if you clicked save) had all of your personally stored phrases. This would have saved me tons of time as a server owner using your text screens for branding I guess you could say.

**Comment by BLEEPBLOOPforLife** [comment]
I just made a pull request for this. :)

**Comment by Cherry** [comment]
Thanks @BLEEPBLOOPforLife. Pulled and pushed to the Steam Workshop. :)
