### ISSUE TITLE
Font changing

### ISSUE THREAD

**Issue by Cherry** [Cherry/3D2D-TextScreens#14]
Implement ability to choose / change fonts?

**Comment by Dellkan** [comment]
Didn't it have that option already before?

**Comment by Cherry** [comment]
Not that I can recall? Right now, it's just doing;

https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/entities/sammyservers_textscreen/cl_init.lua#L5-L13

**Comment by Dellkan** [comment]
Oh. Well, at any rate, I created a complete system for custom fonts, including a full gui, for the commercial variant of zones. Maybe we can reuse that?

**Comment by Cherry** [comment]
Definitely a possibility - that would be awesome! :+1:

**Comment by Dellkan** [comment]
Well, it's a possibility. Don't have gmod installed, nor the time to put it together for you though. If you'd like, I can get you the source code to play around with.

**Comment by Cherry** [comment]
I'd appreciate it! :)

**Comment by Cherry** [comment]
Resolved in #30. Closing.
