### ISSUE TITLE
Problem 3D2DtexteScreen

### ISSUE THREAD

**Issue by SlayerzYT** [Cherry/3D2D-TextScreens#16]
Now since 3day i dont see my textscren permanent "im superadmin". and the players cant ues this item ... :/ help pls and thank for reply to steam workshop

[3D2D Textscreens] lua/weapons/gmod_tool/stools/textscreen.lua:56: attempt to call method 'SetLine' (a nil value)
1. LeftClick - lua/weapons/gmod_tool/stools/textscreen.lua:56
2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:254

**Comment by Cherry** [comment]
Please disable all other addons and report if this issue still occurs. I don't see how this could happen (and am unable to reproduce), without another addon removing the entity as soon as it's being created.

**Comment by SlayerzYT** [comment]
I found thank you for the tip :)
this was in conflict addons

 http://steamcommunity.com/sharedfiles/filedetails/?id=239222059

**Comment by Cherry** [comment]
Thanks for the update! Glad you figured it out!
