### ISSUE TITLE
PermaTextscreen Issue

### ISSUE THREAD

**Issue by TekBob** [Cherry/3D2D-TextScreens#17]
Hello,
Every time I try to make a perma textscreen, it says 'Textscreen made permament and saved.', but when I restart the server, it isn't there. Please help. I'm switching hosts and it works on my old server.

Thanks,
TekBob

**Comment by AMD-NICK** [comment]
Any error in the server console?

**Comment by TekBob** [comment]
Fixed it. My p_nlr_zones addon was blocking it. I enabled Plogs for it, even though I was told it's no longer supported. That's what fked it up. Thanks for replying anyways.

**Comment by Cherry** [comment]
Thanks @TekBob!
