### ISSUE TITLE
More textscreens for Admins (ULX, Fadmin)

### ISSUE THREAD

**Issue by StolenName** [Cherry/3D2D-TextScreens#19]
Is there a way to get more Textscreens for Admins or Superadmins on a gmod server for like ULX or Fadmin (Darkrp)

**Comment by Cherry** [comment]
Not within the scope of this addon, sorry.  You'd need to find an admin modification that would allow differing prop, etc limits per rank on the server. For example: http://forums.ulyssesmod.net/index.php?topic=5269.0 - I have no idea if that still works, but for your reference.

**Comment by Cherry** [comment]
Closing this. Thanks!
