### ISSUE TITLE
Bounding box issues

### ISSUE THREAD

**Issue by Cherry** [Cherry/3D2D-Textscreens#21]
After creation, textscreen refuses to orientate "flush" with the surface, if moved away from it. Likely cause is the prop we're using.

On place: https://jross.me/l/6jmkt
Attempting to move: https://jross.me/l/sftly
Video: https://jross.me/l/r9qsn

**Comment by BLEEPBLOOPforLife** [comment]
Created a pull request fixing this. :)

**Comment by Hackcraft** [comment]
From my testing, it was the `self:SetMoveType(MOVETYPE_NONE)` which stopped the entity object from using the physics object's collision, so instead it uses AABB.

**Comment by Cherry** [comment]
@Hackcraft I see you started a branch at https://github.com/Hackcraft/3D2D-TextScreens/tree/bounding_box_issue with some fixes that were looking good. 👍 Any more developments with this issue?

**Comment by mcNuggets1** [comment]
I already fixed it for my servers ages ago.
Just make it a physics object, no need to make it bigger.

Freeze it upon spawn and freeze it again when finished moving.

**Comment by Cherry** [comment]
@mcNuggets1 Would you like to make a pull request for this?

**Comment by mcNuggets1** [comment]
I am extremely lazy. I don't really enjoy doing pull requests, you could add me on steam (https://steamcommunity.com/id/mcnuggets1908/) and I could send you my code.
