### ISSUE TITLE
killing fps on big servers.

### ISSUE THREAD

**Issue by Aka7tsu4** [Cherry/3D2D-TextScreens#25]
can you make a viewdistance convars/configurable for this addons?
that should be useful as hell because 25textscreens kills fps....

**Comment by Cherry** [comment]
@Aka7tsu4 This is definitely possible, yes. I'll see about implementing a client convar this weekend. Thanks for the suggestion!

**Comment by Aka7tsu4** [comment]
do it.
that should help so much server. :)

**Comment by Cherry** [comment]
Pushed this in https://github.com/Cherry/3D2D-TextScreens/commit/3774503833791cab0f910eb0937c8901c43ebae7.
`ss_render_range` will control the render range localy. It defaults to 1500 but can be adjusted to any number you like. Higher numbers will of course impact performance more. I've tested it briefly, but please let me know if you run into any issues.
