### ISSUE TITLE
Glitched text

### ISSUE THREAD

**Issue by Ramperson** [Cherry/3D2D-TextScreens#26]
When I spawn it I noticed that the text can not be combined with the object for which it was created, and it does not create exactly (I writed on Steam)(Writed by Google Translate 😄)

There's a image that shows the glitch:

![20161229215944_1](https://cloud.githubusercontent.com/assets/24832357/21554859/66226fa2-ce13-11e6-8097-7334b4ec2fe5.jpg)

![20161229215954_1](https://cloud.githubusercontent.com/assets/24832357/21554898/b36fb062-ce13-11e6-9a35-9b1e61647b49.jpg)

I wan't some help or update with repair (and update with better quality for small sizes of text)

**Comment by Cherry** [comment]
Thanks for the report @Ramperson. 

Does this still happen if you add `-dxlevel 95` to your Garry's Mod startup options, and run without any other addons? I'm unable to replicate this in my testing.

**Comment by Ramperson** [comment]
I don't know, I will check it.

**Comment by Cherry** [comment]
Closing this issue. Feel free to re-open or create another @Ramperson if the issue still occurs.
