### ISSUE TITLE
https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/weapons/gmod_tool/stools/textscreen.lua#L64

### ISSUE THREAD

**Issue by notcake** [Cherry/3D2D-TextScreens#34]
https://steamcommunity.com/workshop/filedetails/discussion/109643223/1621724915769260315/

https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/weapons/gmod_tool/stools/textscreen.lua#L64
`tonumber` returns a `number` or `nil`

**Comment by Dellkan** [comment]
This seems accurate.

While we do check for textscreen count for player <= limit before spawning, the count isn't incremented before after the error occurs. It can be reproduced by nulling one of local convars. By doing so, it will error out before ownership, and count is applied, and so it will always think that the player in question has zero textscreens, allowing you to proceed.

Should fix both by avoiding nil, and also by moving count increment, and ownership to right after spawn

**Comment by Cherry** [comment]
Thanks. Fixed in https://github.com/Cherry/3D2D-TextScreens/commit/5f4428463659cb8d69a53921c8bb186dbfa324b7.
