### ISSUE TITLE
Cant use feature on multiplayer.

### ISSUE THREAD

**Issue by Idontwannasignup** [Cherry/3D2D-TextScreens#36]
Hiya.

Whenever I join any multiplayer server that uses 3d2d textscreen, I cant use the presets option, or the font option. Where it would normally display the presets drop down menu, nothing is there and it just says line 1 and has the text boxes. Presets works perfectly fine in single player but for some reason just wont work on these servers. Is this a client side, or server side issue? 

Any help would be appreciated. Thanks.

**Comment by Idontwannasignup** [comment]
Nvm solved

**Comment by Cherry** [comment]
@Idontwannasignup Could you share what the resolution was? It may help other users in the future if they have the same issue.
