### ISSUE TITLE
Text screens don't draw when looking behind in third person

### ISSUE THREAD

**Issue by Hackcraft** [Cherry/3D2D-TextScreens#39]
This is a very minor bug which came about because of the face check which only allows one face to be drawn. The check uses `ply:GetShootPos()` which will not necessarily be the position the player is looking from when using third person. It could even be considered a feature to stop your screen from being filled up with text when you've walked past a screen in third person(the camera, following the player from behind), by which point you don't need to see it anyway.

[Bug view](https://imgur.com/a/vzPmWaz)
[Feature view](https://www.youtube.com/watch?v=ogOsS7BaR7k)

I don't think much can be done about it without rolling back the performance update but it's probably not going to be noticed by most people.

**Comment by mcNuggets1** [comment]
I dont think there is a possibility in gmod to access the rendering point vector and angles.

**Comment by Cherry** [comment]
Is there a reliable way to determine if a user is in thirdperson mode and then just draw it on both sides? Probably not - I imagine there's too much variance in how `CalcView` is used.

**Comment by Cherry** [comment]
Closed in https://github.com/Cherry/3D2D-TextScreens/commit/e2db3cd45408a731cb92fb54dd2af50d7af4c8b6.
