### ISSUE TITLE
Configuration Suggestion

### ISSUE THREAD

**Issue by Fleepy** [Cherry/3D2D-Textscreens#41]
I feel like you should be able to edit the text/logo when you select the tool in the Spawnmenu.
For example:
Right now its set as the default logo.
If the addon had a setting to change the logo (Whether it being by Imgur and other image providers, or by the addons material folder) and or text, it would look like this in the config:
`
textscreenLogo = "image" -- Two options, image and text. Text is for something custom. image is for making the header of the tool to something custom or the default. You can use links that end in .png, .jpeg and .jpg. 

textscreenHeaderText = "3D2D Textscreens" -- This has no effect unless textscreenLogo is set to "text"
`

I hope you take this into consideration.

**Comment by Cherry** [comment]
Thanks for the suggestion! What’s the use case for something like this? Allowing servers to customise the logo? From a branding perspective, I’m not sure how I feel about that, but I’ll think about it.

**Comment by Hackcraft** [comment]
We can use call SetFont in pcall to see if the font has been created, if not then set a fallback. The only problem is that it'll still send errors to the server. Unless we can think up a better fix.

`surface.CreateFont` Doesn't return success :(

All these fonts should be fine.
https://github.com/Facepunch/garrysmod/tree/master/garrysmod/resource/fonts

**Comment by Cherry** [comment]
@Hackcraft I assume this reply was meant for issue https://github.com/Cherry/3D2D-Textscreens/issues/41? 😃

**Comment by Hackcraft** [comment]
@Cherry #42

**Comment by Cherry** [comment]
I'm going to go ahead and close this issue. I don't really see a need for allowing servers to change the logo/name of the tool, and it could lead to confusion with any custom versions/edits of the tool.

If you have anything to add, please feel free to reply.
