### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by PicklesxD** [Cherry/3D2D-Textscreens#42]
This is part of what is spammed in console.

Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'Default'!
Failed creating font 'Railway'!
Failed creating font 'DeJaVu Sans'!
Failed creating font 'DejaVu Sans'!
Failed creating font 'DejaVu Sans'!
Failed creating font 'Exo'!
Failed creating font 'Exo'!
Failed creating font 'Exo'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'DejaVu Sans'!
Failed creating font 'DejaVu Sans'!
Failed creating font 'dejavu sans mono'!
Failed creating font 'DermaDefault'!
Failed creating font 'DermaDefault'!
Failed creating font 'digital-7'!
Failed creating font 'DermaDefault'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'CloseCaption_Bold'!

**Comment by Cherry** [comment]
I've just pushed an update that removes a consistently erroring font, `boogaloo` and fixes the declaration of `Trebuchet`. You shouldn't see any more font errors as result of this addon.
