### ISSUE TITLE
Textscreens Causing engine errors.

### ISSUE THREAD

**Issue by genokoenig** [Cherry/3D2D-Textscreens#46]
Alright, so a couple months ago one of my friends would engine error, and removing textscreens fixed the issue and i readded it last night and now it is back.

Players will only recieve engine errors with no context.

I know for a fact it is textscreens as i have removed it and players can join, then when i add it again they engine error.

For some reason i was able to get ingame and now all of the perma textscreens are weapons

you will find a picture below
alot of my players have commented on the workshop page as i run a popular server
sorry for the workshop spam

https://media.discordapp.net/attachments/506009503305826305/506357783147577344/unknown.png?width=1202&height=677

If you can help me fix this issue (obviously i need textscreens) I will gladly donate to you 

Thanks for reading my report
Geno

**Comment by Cherry** [comment]
Hi Geno,

Thanks for the report. I did push a change over the weekend which may have inadvertently switched some font indexes around, causing the weapons font to now be where `boogaloo` was - you’ll have to recreate the textscreens to resolve this.

In regards to the engine errors, that’s a lot more tricky. Do the errors generate any crash reports or `mdmp` files? Is it specific maps? Is there a sure-fire way I can reproduce the issues?

**Comment by genokoenig** [comment]
No, there is no reasoning behind it, i put ONLY textscreens on a test server and the same thing happened...
Im thinking maybe the players have something wrong with their .gmad?

**Comment by Cherry** [comment]
That's quite unlikely. 

I'll need you to gather some more information from users that are crashing please so I can debug this further, and find any similarities between users.

- What is the output of `mat_dxlevel`?
- Is there a specific map this occurs on?
- Have they tried verifying integrity of game cache?
- Check "Set launch options" in steam library on gmod. What options are set, if any?
- If any crash dumps are created (`.mdmp` files), please provide them.

The more information that can be provided here, the further I can look into this. If you can find a specific setup, map, settings, etc. where I can replicate the issue locally, even better. 👍

**Comment by Cherry** [comment]
I'm going to go ahead and close this. Feel free to create a new issue or update this one if you can provide more information @genokoenig
