### ISSUE TITLE
Cant Permaprop Screens

### ISSUE THREAD

**Issue by Solarmender** [Cherry/3D2D-Textscreens#48]
Hello. I am able to use the permaprop tool for every other item but on textscreens it hits but it doesn't say or do anything. This is a big problem on my server and I need help.

**Comment by Cherry** [comment]
This addon has its own permanent system. As per the description:
> - Permanent text screens
>   - Hold C for context menu, right click on the textscreen, and make the text screen permanent (only works for admins). This is perfect for welcome messages or rules.

We unfortunately can't support PermaProps directly - there's nothing we're doing that shoudl break it, and it does have specific code for textscreens, but, if you want to use PermaProps, you'll need to contact its developer for further assistance. Sorry!

**Comment by Solarmender** [comment]
Ok. Thank you for the quick reply. I will close this issue
