### ISSUE TITLE
PROP IN THE MIDDLE OF TEXTSCREEN

### ISSUE THREAD

**Issue by B4K3R245** [Cherry/3D2D-TextScreens#5]
Look. It's not my addons, you just need to fix it. I disabled them, and still. idk wth I am supposed to do. >:(

**Comment by Cherry** [comment]
I really am unable to reproduce this.

http://imgur.com/KMUrZlz,08Msf2E,rNRr42E,P3EaM2V <- various images from the addon as of today, working absolutely fine.

**Comment by Dellkan** [comment]
Looks good for me as well;

http://steamcommunity.com/sharedfiles/filedetails/?id=409190279 (taken 5 minutes ago)

**Comment by blazedd** [comment]
I can confirm this is working for me as well. (no screenshot, sorry).
