### ISSUE TITLE
Bug with Fading Door tool

### ISSUE THREAD

**Issue by FirecodePublic** [Cherry/3D2D-Textscreens#51]
Hi! Youtuber Urbanichka founded bug and use him to destroy servers.

The bug is: If you have Fading Door TOOL You can select all functions in it like activate immediately, etc and click to Text screen and Owner text is removed and you can't delete THIS TEXT this is very bad, you only need to clear the card, but the players are playing. I hope you understand I used google translator.

Youtuber - Urbanichka

**Comment by Cherry** [comment]
Thanks for the bug report, I think I understand. I'll investigate as soon as I can.

**Comment by FirecodePublic** [comment]
Sorry i mean youли

**Comment by FirecodePublic** [comment]
Reopen

**Comment by Cherry** [comment]
No, I'm unable to replicate the issue, sorry. Let me know if I can clarify anything from my previous message.

**Comment by mcNuggets1** [comment]
Give us a goddamn video.
I'm still receiving e-mails from an email account I don't have github access to.

**Comment by FirecodePublic** [comment]
https://www.youtube.com/watch?v=gLg4q3sd4X0

**Comment by Cherry** [comment]
Is there a specific timestamp in this video where I can see the issue? That looks to be on a server with a lot of other addons too. I really need a vanilla setup and specific steps to replicate the issue. See my comment at https://github.com/Cherry/3D2D-Textscreens/issues/51#issuecomment-459189857 for further details.

**Comment by Cherry** [comment]
I'm going to close this. If you can provide more information @FirecodePublic I'd be happy to take another look.
