### ISSUE TITLE
3D2D Textscreens not loading when I startup my server

### ISSUE THREAD

**Issue by Kurkiie** [Cherry/3D2D-Textscreens#53]
So I used to own a StarwarsRP server, I have the workshop collection setup and it automatically downloads the addons. I had 3D2D Textscreens on that server and it worked fine, then I started a DarkRP server and that is where the problem started. When I got the workshop collection setup with 3D2D Textscreens it gave me "Error, cannot read the downloaded file". Every other addon was fine. Then I got the github file and i transfered it using FileZilla to my server, still doesnt work. I have no idea how to fix this issue.
![edrer](https://user-images.githubusercontent.com/50068727/56860337-e1273f00-6995-11e9-9231-68374cb25fab.PNG)

**Comment by Cherry** [comment]
Thanks for the report. Firstly, I wouldn't recommend manually installing via GitHub, especially if you're also trying to install via the workshop - that's going to cause weird issues, especially when the workshop variant updates and your local one doesn't.

As for the download issue, my only guess is that the download was corrupted and stored in a bad state in cache. 

Please stop your server and remove the following files/folders:
- `~/Steam/appcache/httpcache`
- `~/steam_cache`
- `~/garrysmod/cache/srcds`

Also remove any manually installed versions of 3D2D Textscreens.

Start the server up again and it should re-download everything. It'll take a bit longer to startup as we've cleared all of the cache, but it should resolve any issues with the download being corrupted.

Beyond that, I can only really recommend a re-install of your server, as I'm not able to replicate this:
![](https://up.jross.me/1hbuz)

**Comment by Kurkiie** [comment]
> Thanks for the report. Firstly, I wouldn't recommend manually installing via GitHub, especially if you're also trying to install via the workshop - that's going to cause weird issues, especially when the workshop variant updates and your local one doesn't.
> 
> As for the download issue, my only guess is that the download was corrupted and stored in a bad state in cache.
> 
> Please stop your server and remove the following files/folders:
> 
> * `~/Steam/appcache/httpcache`
> * `~/steam_cache`
> * `~/garrysmod/cache/srcds`
> 
> Also remove any manually installed versions of 3D2D Textscreens.
> 
> Start the server up again and it should re-download everything. It'll take a bit longer to startup as we've cleared all of the cache, but it should resolve any issues with the download being corrupted.
> 
> Beyond that, I can only really recommend a re-install of your server, as I'm not able to replicate this:
> ![](https://camo.githubusercontent.com/cb2d9675adfdf9166f0fc52dabd5b1690eefc0ea/68747470733a2f2f75702e6a726f73732e6d652f316862757a)

Hello, I tried deleting all of the files in the mentioned folder. I have done that, and now all of the addons that I had in my workshop have an error....

**Comment by Cherry** [comment]
If they're all erroring now, it sounds like your server has some kind of connectivity issues. That's unfortunately not really something I can help you solve - sorry!

**Comment by Kurkiie** [comment]
Thanks anyways.

**Comment by Cherry** [comment]
I'm going to go ahead and close this. Sorry I couldn't help further. If you find an issue with textscreens directly, feel free to update the issue.
