### ISSUE TITLE
Text Flickering

### ISSUE THREAD

**Issue by hinzy00** [Cherry/3D2D-Textscreens#54]
I've created a map for Gmod and your addon works perfectly fine **before** I pack any custom content into my map using [VIDE](https://www.tophattwaffle.com/downloads/vide/). Once the map has custom content packed inside I encounter a bug where text flickers and disappears at random angles/distances and locations around the map. I'm completely stumped as to what could be causing this and any help would be gladly appreciated. I've recorded an example of the issue which seems to happen on two different maps that I've created, both have custom content packed: https://media.giphy.com/media/RicihyoDoa4Zvgo1YW/giphy.gif

**Comment by Cherry** [comment]
Thanks for the report!

This is definitely an interesting one. It kinda looks like a form of z-fighting? Does the issue persist if you move the screens away from the wall slightly?

I'm honestly not familiar whatsoever with VIDE, so there's probably not going to be a whole lot I can do here, but I'd be interested to know if you find anything else.

**Comment by hinzy00** [comment]
> 
> 
> Thanks for the report!
> 
> This is definitely an interesting one. It kinda looks like a form of z-fighting? Does the issue persist if you move the screens away from the wall slightly?
> 
> I'm honestly not familiar whatsoever with VIDE, so there's probably not going to be a whole lot I can do here, but I'd be interested to know if you find anything else.

Moving the textscreens away doesn't seem to help the issue, unfortunately. I'm going to keep investigating and perhaps try an alternate tool and seeing if the problem persists. But honestly I have no clue as to what could be causing it

**Comment by Cherry** [comment]
I'm going to go ahead and close this issue. I don't think it's something I have much control over. If you have any more information, feel free to update this, or create a new issue.
