### ISSUE TITLE
Textscreens unmoveable.

### ISSUE THREAD

**Issue by Hoofys** [Cherry/3D2D-Textscreens#55]
I can't legit remove textscreens.

I tried deleting the data of it
i tried making it perma and again but no work

help please.

**Comment by Cherry** [comment]
Thanks for the report. I need a lot more information if I'm to help debug this those.

- Your title states "unmoveable", but your text states you "can't remove" textscreens. Could you clarify exactly what this means?

- Are you running any other addons? Does the issue persist if you disable all other addons?

- Could you provide some precise steps to replicate what you're describing?

**Comment by Cherry** [comment]
I'm going to go ahead and close this issue. If you can provide more information, please feel free to update this or create a new issue.
