### ISSUE TITLE
Textscreen menu partially blank

### ISSUE THREAD

**Issue by tristan2998** [Cherry/3D2D-Textscreens#59]
Most of the textscreen menu is blank below the reset buttons. When you open the tool, the console gives this error: 
[ERROR] addons/3d2dtextscreens/lua/weapons/gmod_tool/stools/textscreen.lua:165: attempt to index upvalue 'textscreenFonts' (a nil value)

**Comment by Cherry** [comment]
Thanks for the report @tristan2998. I'm unable to replicate this currently.

Does this happen if you use the workshop variant of the addon, without any other addons installed?

**Comment by tristan2998** [comment]
It happens with both workshop and github releases

**Comment by Cherry** [comment]
Can you please confirm it still happens if you remove all other addons? I can not replicate this on the `public` or `dev` branches of Garry's Mod.

**Comment by tristan2998** [comment]
Yes, I have ran my server with only the addon installed, and it still does it.

**Comment by tristan2998** [comment]
If it helps to know, for some reason, the Gmad extractor adds a random character to the beginning and end of each .lua. I fixed the issue but it didn't change anything. But the console sometimes says to addons/3d2d textscreens/lua/weapons/gmod_tool/stools/textscreen.lua:165: attempt to index upvalue 'textscreenFonts' (a nil value). Attatching my .lua file just to be sure
[textscreen.txt](https://github.com/Cherry/3D2D-Textscreens/files/3848785/textscreen.txt)

**Comment by tristan2998** [comment]
[3d2d textscreens.zip](https://github.com/Cherry/3D2D-Textscreens/files/3848808/3d2d.textscreens.zip)
This is the addon folder

**Comment by Cherry** [comment]
Yeah - that .zip is very wrong. It's missing the `autorun` folder, and many files are missing characters at the start, which is going to cause _lots_ of issues. Whatever extractor tool you're using isn't working. 

Please install the addon using a Workshop Collection as per https://wiki.garrysmod.com/page/Workshop_for_Dedicated_Servers.

**Comment by tristan2998** [comment]
That resolved the issue, thank you.

**Comment by Cherry** [comment]
Thanks @tristan2998, I'm glad it's working for you now!
