### ISSUE TITLE
Always permanent

### ISSUE THREAD

**Issue by Awesome123123** [Cherry/3D2D-TextScreens#6]
I am having an issue where when ever a superadmin puts down a textscreen it is automatically made permanent. What should I do to fix it?

**Comment by Cherry** [comment]
That's not really possible without an admin explicitly right clicking and hitting "make permanent", hmm.

Client side: https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/autorun/textscreens_util.lua#L155
Server side: https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/autorun/textscreens_util.lua#L75

As you can see, the "make permanent" command is only ever executed explicitly by an admin.

Do you have any other perma-props based addons on your server?

**Comment by Awesome123123** [comment]
Well all my admins are having this issue. So when they hit c on the prop it does say remove perma screen even to players. I do not have any perma prop addons on my server

**Comment by Cherry** [comment]
Does the issue continue if you disable all other addons / custom scripts, and run on a sandbox gamemode?

I'm unable to replicate the described issue so far.

**Comment by Awesome123123** [comment]
I have tracked it down to the data file that saves the perma text screens.

**Comment by Cherry** [comment]
The data file that this addon creates is ONLY ever written to in the conditions as previously described. Whilst I appreciate the assistance, providing me with the file isn't going to yield any results.

Does the issue continue if you disable all other addons / custom scripts, and run on a sandbox gamemode?

**Comment by Awesome123123** [comment]
I did. It is the data folder. I pulled it and it worked perfectly
