### ISSUE TITLE
adding more max text

### ISSUE THREAD

**Issue by EnviousOne** [Cherry/3D2D-Textscreens#65]
Hello, i've installed the addon onto my server and its working fine, i wanted to make the max textscreen amount higher, i looked all over online and found out how but theres no files to edit.
I tried to extract the files but instead of 1 folder i got 3-4 different files/folders
so i played around with it moved things around put things in certain places but nothing. 
im using WinSCP to transfer files. Please help me~!

**Comment by Cherry** [comment]
Hi there,

Firstly, don't extract the addon - no support is offered for this setup, and we recommend you only install it through the Workshop.

As for increasing the number of max textscreens though, check out the description of this addon:

> `sbox_maxtextscreens` controls the maximum amount of text screens that each player can spawn. This defaults to 1. This cvar only exists on the server, so make sure it's set via RCON, or in something like `server.cfg`.

So simply add something like `sbox_maxtextscreens 10` to your `server.cfg` file on a new line and restart your server.

**Comment by EnviousOne** [comment]
ive tried that, but every time i restart the server its no longer in the server.cfg. Basically just gets deleted every time i restart.

**Comment by Cherry** [comment]
You must have something else interfering on your server, sorry. On a fresh vanilla install, the above instructions work fine for me. If you can provide me steps to replicate the issue on a freshly installed gmod server, I'd be happy to take a closer look.

**Comment by EnviousOne** [comment]
ill try and take out all the addons and see if that changes anything

**Comment by EnviousOne** [comment]
Okay that seemed to work, 
![image](https://user-images.githubusercontent.com/50977165/83580901-f3e53f00-a4d8-11ea-835d-029e240970f1.png)
![image](https://user-images.githubusercontent.com/50977165/83580910-fba4e380-a4d8-11ea-8777-bff81e968cd3.png)
these are my addons when it WASNT working

**Comment by deadmonstor** [comment]
Nothing from lua can edit server.cfg meaning that none of these addons is able to break it from being the cfg file. 


Make sure you are saving the file, you can check if it is set by putting "sbox_maxtextscreens" in the server console and checking the number after the "="
