### ISSUE TITLE
Textscreens physgun issue

### ISSUE THREAD

**Issue by Bambob01** [Cherry/3D2D-Textscreens#66]
All I did was place a text screen I'm unable to move it with my physgun at all it's like it's frozen

**Comment by Cherry** [comment]
Thanks for the report. Can you please provide significantly more information so I can debug this though?

- Are you running any other addons? Does the issue persist if you disable all other addons?
- Could you provide steps for replication? A step-by-step guide for how I can replicate this in a vanilla environment.

**Comment by Bambob01** [comment]
I will upload a video I'm a manager of a server and have not added any new addons since the issue started it just kicked up out of no where ill upload the video lemme start ibs

**Comment by Bambob01** [comment]
Whilst I start my gmod I would just like to add

I do not know how to replicate this it just happened out of nowhere we didn't make any changes other than change jobs.lua 

If you wish to check it out I can DM you our server ip and you can't see the issue there but I'll send the video from my end so u can see what's up

**Comment by Bambob01** [comment]
Sorry for the slow reply!!

Here is the video hope it helps!!

https://youtu.be/_yu8qg1xtnU

**Comment by Cherry** [comment]
Looking at that video, it appears to be on a highly customised DarkRP server, with lots of other addons. There could be any number of unknown incompatibilities.

To look at this further, I'm going to need steps to replicate in a vanilla environment and no other addons installed, sorry.

**Comment by Cherry** [comment]
Closing this as no replication steps in a vanilla environment have been provided. Please feel free to open another issue if you have more info.
