### ISSUE TITLE
RGB spectrum cycling (rainbow text)

### ISSUE THREAD

**Issue by darkmodee** [Cherry/3D2D-Textscreens#67]
Hi, made a comment on the Steam Workshop page on Textscreens, I would like this feature to be added:
In the color section of the text, make an option where you can make the text cycle through RGB colors (rainbow)

Just another thought adding onto color changing, possibly add a gradient color option, too. More colors with the text would open up way more possibilities especially for servers like DarkRP and servers using text-screens to give info to players and make it _**pop.**_

**Comment by Cherry** [comment]
Thanks for the suggestion! I'd welcome a PR for this, but am unlikely to be able to get to this myself in the near future.

**Comment by FrezZyyy** [comment]
@Cherry i actually have an edit where rainbow is an option for textscreens if you wanna take a look at it

**Comment by Cherry** [comment]
@FrezZyyy If you'd like to submit a PR with these changes, I'd be happy to take a look!

**Comment by KingChris23** [comment]
@FrezZyyy Is there anyway I could test the edit for my darkrp server?

**Comment by KennyHarrer** [comment]
Make a per line toggle convar? ex. textscreen_line1_rainbow = 1/0
then you can use hsv and curtime for the rainbow effect

**Comment by KennyHarrer** [comment]
```
local rainbowSpeed = 100
HSVToColor( CurTime() * rainbowSpeed % 360, 1, 1 )
```

Here is an example of the aforementioned HSV

**Comment by KingChris23** [comment]
do i put this in server.cfg?

**Comment by KingChris23** [comment]
Where would i put this?

**Comment by KingChris23** [comment]
@KennyHarrer Where would i put this?

**Comment by KennyHarrer** [comment]
@KingChris23 You don't put it anywhere. That simply returns a rainbow color.

**Comment by TomDotBat** [comment]
https://github.com/TomDotBat/3D2D-Textscreens
My version of TextScreens has HSV and donator restrictions built into it ([config here](https://github.com/TomDotBat/3D2D-Textscreens/blob/master/lua/textscreens_config.lua)). I haven't made it into a PR due to some of the major changes made in my version such as the entity class name change and perma system removal. So only use mine if you're aware of the affect it will have.

**Comment by Cherry** [comment]
> [TomDotBat/3D2D-Textscreens](https://github.com/TomDotBat/3D2D-Textscreens)
> My version of TextScreens has HSV and donator restrictions built into it ([config here](https://github.com/TomDotBat/3D2D-Textscreens/blob/master/lua/textscreens_config.lua?rgh-link-date=2021-01-18T11%3A07%3A45Z)). I haven't made it into a PR due to some of the major changes made in my version such as the entity class name change and perma system removal. So only use mine if you're aware of the affect it will have.

This is awesome! If you do find a way to PR any of the useful bits and pieces in your fork, that would be fantastic.

**Comment by Cherry** [comment]
Added in #73 thanks for @TomDotBat 🎉
