### ISSUE TITLE
Flashlight stops render

### ISSUE THREAD

**Issue by BigBl0b** [Cherry/3D2D-Textscreens#77]
- https://gyazo.com/9aa782d176407859fbb9b222b33cda7b
have you flashlight on and walk up to a text screen.

**Comment by Cherry** [comment]
Thanks for the issue report!

I can't seem to replicate this in a vanilla sandbox environment though: https://up.jross.me/jqkvv0in

Perhaps this is something specific to your environment or that server? Can you provide replication steps in a vanilla sandbox environment?
