### ISSUE TITLE
Invisible Textscreens

### ISSUE THREAD

**Issue by WelshBanana** [Cherry/3D2D-Textscreens#78]
Researching into the issue a bit more I've noticed other people have had a similar problem but not quite the same, I'll do my best to explain it as best as I can.
Upon making a text screen whether you try to 'Perma prop' or 'Perma text screen' the text screen will refresh as normal and remain there. However upon a server restart, the text screen will then turn invisible, it's still there as you can still interact with it through the context menu and if you permit prop a Perma text screen after having the bug it will return as though nothing has happened but if the server restarts again it does not care and will go back to being invisible. Oddly though this does not happen with every text screen, only with about half, I had tested it with a friend where we placed 10 text screens each together, 'perma'd' them, restarted the server and then none of them had saved! Out of a sample size of 20, 0 had been saved which needless to say is an intolerable result. This leads me to believe it may be a database issue however I'm unsure and to be truly honest completely flustered as to what could be doing this. I have tried both the git and steam versions to no avail.

The only things that are being printed in the console in regards to 3d2d are the following
[3D2D Textscreens] Spawning textscreens...
[3D2D Textscreens] Spawned 44 textscreens for map rp_titan_base_bananakin

Thanks.

**Comment by Cherry** [comment]
Thanks for the detailed report.

Do you have a `sammyservers_textscreens.txt` file in your `data` folder that can currently replicate this? If so, I'd love to get a copy of that.

Once this happens, does it _always_ happen, or does it seem to be different screens that are visible/invisible on every restart? Does it happen on multiple maps, or just some specific ones?

**Comment by WelshBanana** [comment]
It varies as I said, sometimes it works and others it just doesn't appear. From everything I've seen as of yet it has led me to deduce that some sort of information isn't being recorded successfully. This especially doesn't make sense as when you perma prop it then it suddenly returns from the dead, apart from rainbow text screens, the text is there but it no longer has the rainbow effect. I'm quite honestly clueless as to what could be causing it, I've tested it so much as to see if I can find any conceivable patterns that lead to a specific glitch however there are none it truly is random. I have attached the requested file to this comment for you to review. In regards to the question you asked just to clarify, it is purely random however ones that are affected are invisible upon a server restart whereas ones that have been successful work just as intended.

Thanks, I appreciate the support!

[sammyservers_textscreens.txt](https://github.com/Cherry/3D2D-Textscreens/files/6993292/sammyservers_textscreens.txt)

**Comment by Maverick238** [comment]
Hi we are having a very similar problem on our Server where only 50% of the signs are rendering (They still spawn):

[sammyservers_textscreens.txt](https://github.com/Cherry/3D2D-Textscreens/files/8028728/sammyservers_textscreens.txt)

And this is our collection if it is important:

https//steamcommunity.com/sharedfiles/filedetails/?id=2015394018

**Comment by Cherry** [comment]
It looks like you're using a non-official version of the addon, which I can't provide support for I'm afraid, sorry.

If you can provide steps to replicate this issue in a sandbox environment using the official addon and no other addons installed, I'd be happy to investigate further.

**Comment by Maverick238** [comment]
@Cherry we tried it with normal 3D2D Textscreens again and we found out that z_anticrash was interfering with the spawning of the textscreens by ghosting it. Could it be that a ghosted Textscreen isn't rendered proberly ?

**Comment by Cherry** [comment]
That's very possible. I'm not familiar with `z_anticrash` and what it does with "ghosting". If you remove that addon temporarily, do things work correctly?
