### ISSUE TITLE
Problem localization

### ISSUE THREAD

**Issue by thierryhoude** [Cherry/3D2D-Textscreens#81]
Hello, I have a problem with the localization on my server I only have the gamemode darkrp and in addons darkrp modification and the 3d2d textscreen up to date and the name, the description ECT... exemple: #tool.textscreen.name #tool.textscreen.desc #tool.textscreen.left ECT...

**Comment by Cherry** [comment]
Thanks for reporting the issue. What language are you using in-game? It's possible that if you're using a language not present in https://github.com/Cherry/3D2D-Textscreens/tree/main/resource/localization, there may be issues. 🤔

**Comment by thierryhoude** [comment]
hello, I use the french language on the game (fr)

**Comment by Cherry** [comment]
This should now be resolved, and an update pushed to the Workshop. 👍
