### ISSUE TITLE
Not Loading into Spawnmenu tools on Ubuntu server Help

### ISSUE THREAD

**Issue by bigbadbeee** [Cherry/3D2D-TextScreens#9]
I own a server running on ubuntu linux and I have restarted the server many times but the tool gun for the text screen will no show up. Is it because Iam running the server on Linux?

**Comment by Cherry** [comment]
The addon should have no issues functioning in a Linux environment. Are you seeing any Lua errors in your console during startup?

If you follow http://wiki.garrysmod.com/page/Workshop_for_Dedicated_Servers and only have 3D2D textscreens in your collection (with no other addons), does the issue continue?

**Comment by bigbadbeee** [comment]
I fixed it I wasn't using workshop but github
--SOLVED--
-CLOSED-
